### ISSUE TITLE
Having trouble compiling 0.8c from source

### ISSUE THREAD

**Issue by DanBiscotti** [GNS3/vpcs#23] opened 2020-06-12 21:11 UTC
Hi guys,
I'm trying to run vpcs for GNS3 by compiling from source. The latest release on sourceforge is 0.8b, but that seems to have a bug where only 2 chars can be typed before executing.
So trying to compile 0.8c from the current master (30f392f) I go into `src` and run:

`./mk.sh 64`

However I get the following output:

> Makefile.linux:38: warning: ignoring prerequisites on suffix rule definition
> gcc -O2 -m64 vpcs.o daemon.o readline.o packets.o utils.o queue.o command.o dev.o dhcp.o command6.o packets6.o ip.o tcp.o inet6.o dns.o remote.o help.o dump.o relay.o hv.o frag.o frag6.o -o vpcs -lpthread -lutil
> /usr/bin/ld: packets.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: command.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: dev.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: dhcp.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: command6.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: packets6.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: tcp.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: dns.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: dump.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: relay.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> /usr/bin/ld: frag6.o:(.bss+0x0): multiple definition of 'vpc'; vpcs.o:(.bss+0x60): first defined here
> collect2: error: ld returned 1 exit status
> make: *** [Makefile.linux:35: vpcs] Error 1

I've tried googling the errors but can't work out the issue. Grateful for any help, thanks

**Comment by coolabhays** [comment] 2020-06-16 11:23
I'm also having same problem. I also tried with svn and there's also this same problem for multiple defination

**Comment by danielhass** [comment] 2020-06-18 16:52
I'm the maintainer of the AUR package of `vpcs` and I have users reporting the same error during the compilation. I was able to reproduce this with vpcs-v0.6.2 and vpcs-v0.8beta1 on Arch Linux with gcc-v10.1.0.

**Comment by ChristianCB16** [comment] 2020-06-18 17:36
I have the same problem, maybe is for the OS Manjaro.

**Comment by Un1Gfn** [comment] 2020-06-19 00:23
@danielhass Here is the aforementioned "users". 0.8beta1 doesn't seem to compile, but what is the latest working version AFAYK?

**Comment by coolabhays** [comment] 2020-06-19 05:20
@danielhass Yupp, I also have gcc v10.1.0 and was trying to compile latest vpcs version. Some others have also reported this issue that it's not compiling with gcc v10.1.0

**Comment by Un1Gfn** [comment] 2020-06-19 07:06
```bash
sed -i vpcs.h -e 's#pcs vpc\[MAX_NUM_PTHS\];#extern pcs vpc\[MAX_NUM_PTHS\];#g'
sed -i vpcs.c -e '/^static const char \*ident/a \\npcs vpc[MAX_NUM_PTHS];'
```

Compilation successful :)

**Comment by Un1Gfn** [comment] 2020-06-19 07:12
[Here](https://gcc.gnu.org/gcc-10/porting_to.html#common) is **exactly** why this happened after updating to GCC 10

**Comment by DanBiscotti** [comment] 2020-06-19 09:34
Yep that worked for me. Thanks!

**Comment by danielhass** [comment] 2020-06-20 10:19
@Un1Gfn thanks for the sed fix ;)
As the cause for the compilation error is the incorrect declaration of a global variable in a header file, would you maybe submit a PR with a fix for this so that we don't have to patch this during the packaging?

**Comment by grossmj** [comment] 2021-08-12 02:33
Fixed by PR.

**Closed by grossmj** 2021-08-12 02:33 UTC
